name: diff test

on:
  push

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx6g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3.9.0
        with:
          distribution: 'zulu'
          java-version: 19

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2

      - uses: dawidd6/action-download-artifact@v2
        with:
          name: screenshots
          path: app/build/outputs/roborazzi
          workflow: test.yaml
          branch: main
      - name: compare test
        run: |
          ./gradlew roborazzi-gradle-plugin:build --stacktrace
          echo '<resources><string name="first_fragment_label">This is compare test screen! Compare me!</string></resources>' > app/src/main/res/values/strings_for_test.xml
          ./gradlew app:compareRoborazziDebug --stacktrace
          # Check if there are difference with app/build/outputs/roborazzi/test_compare.png
          find app/build/outputs/roborazzi
          file_path="app/build/outputs/roborazzi/com_github_takahirom_roborazzi_sample_ManualTest_captureRoboImageSample_compare.png"
          if [ ! -f "$file_path" ]; then
            echo "Error: File $file_path not found."
           exit 1
          else
            echo "File $file_path found."
            exit 0
          fi

      - name: verify test
        run: |
          ./gradlew roborazzi-gradle-plugin:build --stacktrace
          echo '<resources><string name="first_fragment_label">This is verify test screen! Verify me!</string></resources>' > app/src/main/res/values/strings_for_test.xml
          ./gradlew app:verifyRoborazziDebug --stacktrace --continue
          if [ $? -eq 0 ]; then
            echo "Gradle tests succeeded. The verify task should fail. Reporting failure."
            exit 1
          else
            echo "Gradle tests failed. Reporting success."
            exit 0
          fi
      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: screenshot-diff
          path: app/build/outputs/roborazzi
          retention-days: 30

      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: screenshot-diff-reports
          path: app/build/reports
          retention-days: 30

      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: screenshot-diff-test-results
          path: app/build/test-results
          retention-days: 30
